Coşkun Akarsu
GuiderSoft-Team/Group2_Homeworks pull request #35
Opened 2022-11-02 14:41 UTC by CoskunAkrs

Ödev tamamlandı inşallah :)

2022-11-02 14:43 UTC, CoskunAkrs commented
...

2022-11-02 18:10 UTC, gurhanustali requested changes
Şunlar ve bunlar hatalı

2022-11-03 12:20 UTC, CoskunAkrs commented
coşkun tamamladı

2022-11-03 12:45 UTC, gurhanustali approved these changes

2022-11-03 14:18 UTC, closed without merging